-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-07-02T12:17:24.344Z

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "email_verified_at" timestamp,
  "password" varchar(255) NOT NULL,
  "two_factor_secret" text,
  "two_factor_recovery_codes" text,
  "two_factor_confirmed_at" timestamp,
  "remember_token" varchar(100),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "notifications" (
  "id" uuid PRIMARY KEY,
  "type" varchar(255) NOT NULL,
  "notifiable_type" varchar(255) NOT NULL,
  "notifiable_id" bigint NOT NULL,
  "data" json NOT NULL,
  "read_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "password_reset_tokens" (
  "email" varchar(255) PRIMARY KEY,
  "token" varchar(255) NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "sessions" (
  "id" varchar(255) PRIMARY KEY,
  "user_id" bigint,
  "ip_address" varchar(45),
  "user_agent" text,
  "payload" text NOT NULL,
  "last_activity" int NOT NULL
);

CREATE TABLE "cache" (
  "key" varchar(255) PRIMARY KEY,
  "value" text NOT NULL,
  "expiration" int NOT NULL
);

CREATE TABLE "cache_locks" (
  "key" varchar(255) PRIMARY KEY,
  "owner" varchar(255) NOT NULL,
  "expiration" int NOT NULL
);

CREATE TABLE "jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "queue" varchar(255) NOT NULL,
  "payload" text NOT NULL,
  "attempts" smallint NOT NULL,
  "reserved_at" int,
  "available_at" int NOT NULL,
  "created_at" int NOT NULL
);

CREATE TABLE "job_batches" (
  "id" varchar(255) PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "total_jobs" int NOT NULL,
  "pending_jobs" int NOT NULL,
  "failed_jobs" int NOT NULL,
  "failed_job_ids" text NOT NULL,
  "options" text,
  "cancelled_at" int,
  "created_at" int NOT NULL,
  "finished_at" int
);

CREATE TABLE "failed_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" varchar(255) UNIQUE NOT NULL,
  "connection" text NOT NULL,
  "queue" text NOT NULL,
  "payload" text NOT NULL,
  "exception" text NOT NULL,
  "failed_at" timestamp DEFAULT (now())
);

CREATE INDEX "notifications_notifiable_type_notifiable_id_index" ON "notifications" ("notifiable_type", "notifiable_id");

CREATE INDEX ON "sessions" ("user_id");

CREATE INDEX ON "sessions" ("last_activity");

CREATE INDEX ON "jobs" ("queue");

COMMENT ON TABLE "users" IS 'Registered application accounts. Holds credentials, email verification state, and optional two-factor authentication (TOTP) data.';

COMMENT ON TABLE "notifications" IS 'Application notifications on a polymorphic notifiable relation (notifiable_type + notifiable_id). The target model is dynamic, so no single foreign key is declared.';

COMMENT ON TABLE "password_reset_tokens" IS 'Single-use tokens issued for password reset requests, keyed by the user email address.';

COMMENT ON TABLE "sessions" IS 'Driver-based sessions, one row per active browser session.';

COMMENT ON TABLE "cache" IS 'Application cache store: key/value pairs with a Unix expiration timestamp.';

COMMENT ON TABLE "cache_locks" IS 'Atomic locks held within the cache store for coordinating concurrent work.';

COMMENT ON TABLE "jobs" IS 'Pending and in-flight queue jobs.';

COMMENT ON TABLE "job_batches" IS 'Batched jobs tracked as a group with aggregate progress counters.';

COMMENT ON TABLE "failed_jobs" IS 'Jobs that exceeded the maximum retry attempts, retained for inspection and retry.';

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
