[program:octane]
process_name = %(program_name)s_%(process_num)s
command = php %(ENV_ROOT)s/artisan octane:frankenphp --host=0.0.0.0 --port=8000 --admin-host=127.0.0.1 --admin-port=2019
user = %(ENV_USER)s
priority = 1
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stopwaitsecs = 30
environment = LARAVEL_OCTANE="1"
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0

[program:vite]
process_name = %(program_name)s_%(process_num)s
command = pnpm run dev --host
user = %(ENV_USER)s
priority = 2
autostart = %(ENV_WITH_VITE)s
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0

[include]
files = /etc/supervisord.conf
