tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/private.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: SAMEORIGIN
        contentTypeNosniff: true
        referrerPolicy: strict-origin-when-cross-origin
        permissionsPolicy: 'camera=(), geolocation=(), microphone=(), payment=()'
        accessControlMaxAge: 100
        addVaryHeader: true

    security-staging:
      headers:
        customResponseHeaders:
          X-Robots-Tag: 'noindex, nofollow'

    compress:
      compress:
        excludedContentTypes:
          - 'application/grpc'

    traefik-auth:
      basicAuth:
        users: ${TRAEFIK_AUTH}
